export const AUTH_ERROR_CODES = {
  USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_FAILED: "AUTH_FAILED",
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
